import { standardInitialSpecs, StandardSpec } from '@musical-patterns/pattern'
import {
    HAFUHAFU_INITIAL_BASE_DURATION,
    HAFUHAFU_INITIAL_BASE_FREQUENCY,
    HAFUHAFU_INITIAL_EXISTENCE_STYLE,
    HAFUHAFU_INITIAL_KERNEL,
    HAFUHAFU_INITIAL_LAYER_COUNT,
    HAFUHAFU_INITIAL_MODE,
    HAFUHAFU_INITIAL_PITCH_STEP,
    HAFUHAFU_INITIAL_REVERSE,
    HAFUHAFU_INITIAL_SIEVE,
    HAFUHAFU_INITIAL_SIEVE_FRACTAL_REPETITIONS,
    HAFUHAFU_INITIAL_STRETCH_PITCH,
} from './constants'
import { HafuhafuSpec, HafuhafuSpecs } from './types'

const initialSpecs: HafuhafuSpecs = {
    ...standardInitialSpecs,
    [ StandardSpec.BASE_DURATION ]: HAFUHAFU_INITIAL_BASE_DURATION,
    [ StandardSpec.BASE_FREQUENCY ]: HAFUHAFU_INITIAL_BASE_FREQUENCY,
    [ HafuhafuSpec.EXISTENCE_STYLE ]: HAFUHAFU_INITIAL_EXISTENCE_STYLE,
    [ HafuhafuSpec.SIEVE_FRACTAL_REPETITIONS ]: HAFUHAFU_INITIAL_SIEVE_FRACTAL_REPETITIONS,
    [ HafuhafuSpec.SOURCE_KERNEL ]: HAFUHAFU_INITIAL_KERNEL,
    [ HafuhafuSpec.MODE ]: HAFUHAFU_INITIAL_MODE,
    [ HafuhafuSpec.PITCH_STEP ]: HAFUHAFU_INITIAL_PITCH_STEP,
    [ HafuhafuSpec.REVERSE ]: HAFUHAFU_INITIAL_REVERSE,
    [ HafuhafuSpec.SIEVE ]: HAFUHAFU_INITIAL_SIEVE,
    [ HafuhafuSpec.LAYER_COUNT ]: HAFUHAFU_INITIAL_LAYER_COUNT,
    [ HafuhafuSpec.STRETCH_PITCH ]: HAFUHAFU_INITIAL_STRETCH_PITCH,
}

export {
    initialSpecs,
}
